# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: mars.liu@outlook.com
author_name: Mars Liu
has_binder: true
has_settings: true
kind: frontend
labextension_name: litchi
project_short_description: litchi is a ai client for jupyter lab
python_name: litchi
repository: https://github.com/MarchLiu/litchi
test: true

